namespace: nfs
createNamespace: true
serviceAccountName: default

gceStorage: 5Gi
pvcStorage: 1Gi
pvStorage: 1Gi

pvName: nfs-persistent-volume
pvcName: nfs-persistent-volume-claim
nfsServerServiceName: nfs-server
