kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: {{ include "fdp-nfs.fullname" . }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ include "fdp-nfs.fullname" . }}
    spec:
      serviceAccountName: {{ include "fdp-nfs.serviceAccountName" . }}
      containers:
        - name: {{ include "fdp-nfs.fullname" . }}
          image: {{ .Values.nfsProvisionerImage }}
          ports:
            - name: nfs
              containerPort: 2049
            - name: mountd
              containerPort: 20048
            - name: rpcbind
              containerPort: 111
            - name: rpcbind-udp
              containerPort: 111
              protocol: UDP
          securityContext:
            privileged: true
            capabilities:
              add:
                - DAC_READ_SEARCH
                - SYS_RESOURCE
          args:
            - "-provisioner={{ .Values.nfsProvisionerName }}"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SERVICE_NAME
              value: {{ include "fdp-nfs.fullname" . }}
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          volumeMounts:
            - name: export-volume
              mountPath: /export
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      volumes:
        - name: export-volume
          {{- if .Values.onOpenShift }}
          hostPath:
            path: /storage/dynamic
          {{- else }}
          emptyDir: {}
          {{- end }}
