kind: Service
apiVersion: v1
metadata:
  name: {{ include "fdp-nfs.fullname" . }}
  labels:
    app: {{ include "fdp-nfs.fullname" . }}
    app.kubernetes.io/name: {{ include "fdp-nfs.name" . }}
    helm.sh/chart: {{ include "fdp-nfs.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
    - name: rpcbind-udp
      port: 111
      protocol: UDP
  selector:
    app: {{ include "fdp-nfs.fullname" . }}
