{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fdp-nfs.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "fdp-nfs.name" . }}
    helm.sh/chart: {{ include "fdp-nfs.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}
